dist: trusty
language: rust
rust:
- nightly
- stable
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8
    - g++-8
    - cmake
script:
- export CC=/usr/bin/gcc-8
- export CXX=/usr/bin/g++-8
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo build --no-default-features;
  fi
# Check with all features
- cargo check --features simd,atomics,sign_ext,bulk
- cargo build --release --verbose
- cargo test --release --verbose
- cargo test --release --manifest-path=spec/Cargo.toml
- cargo run --example bench-decoder --releas
env:
  global:
  - RUSTFLAGS=--cfg=slow_assertions
  - CC=/usr/bin/gcc-8
  - CXX=/usr/bin/g++-8
