[package]
name = "parity-wasm"
version = "0.21.0"
authors = ["Nikolay Volf <nikvolf@gmail.com>", "Svyatoslav Nikolsky <svyatonik@yandex.ru>", "Sergey Shulepov <s.pepyakin@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/parity-wasm"
homepage = "https://github.com/paritytech/parity-wasm"
documentation = "https://paritytech.github.io/parity-wasm/parity_wasm/"
description = "WebAssembly binary format serialization/deserialization/interpreter"
keywords = ["wasm", "webassembly", "bytecode", "serde", "interpreter"]
exclude = [ "res/*", "spec/*" ]

[dependencies]
log = "0.3"
byteorder = "1.0"
parking_lot = "0.5"
